Jenkinsfile_CNP, Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DMP-390
```
[ ] Yes
[x] No
```
=> DMP-390 Jenksinfiles for automated testing repo

Jenkinsfile_CNP, Jenkinsfile_nightly
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> DMP-390 Update Jenkinsfile

.gitignore, lib/src/main/java/uk/gov/hmcts/darts/automation/pageObjects/package-info.java, lib/src/main/java/uk/gov/hmcts/darts/automation/utils/package-info.java, lib/src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, lib/src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/package-info.java, lib/src/test/java/uk/gov/hmcts/darts/automation/cucumber/testRunner/TestRunner_Cucumber.java, lib/src/test/java/uk/gov/hmcts/darts/automation/cucumber/testRunner/package-info.java
https://tools.hmcts.net/jira/browse/DMP-388
Fix missing class issue
```
[ ] Yes
[X] No
```
=> Dmp 388 initial - updates

lib/src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, lib/src/main/java/uk/gov/hmcts/darts/automation/utils/ScreenShotTaker.java, lib/src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_hooks.java, lib/src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, lib/src/test/resources/cucumber/features/portal/DARTS_Portal.feature
https://tools.hmcts.net/jira/browse/DMP-388
Updates to automation framework:
- adding screenshots on failure
- fixing feature
- other minor updates
```
[ ] Yes
[x] No
```
=> Dmp 388 initial

config/owasp/suppressions.xml
=> Adding CVE suppression to fix build

Jenkinsfile_nightly
=> Fixing nightly pipeline

src/test/resources/cucumber/features/portal/DARTS_Portal.feature
https://tools.hmcts.net/jira/browse/DMP-860
Change My Audios / Transcripts to Your
```
[ ] Yes
[x] No
```
=> DMP-860 Update DARTS_Portal.feature

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/main/java/uk/gov/hmcts/darts/automation/utils/SeleniumWebDriver.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_hooks.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_navigation.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature
https://tools.hmcts.net/jira/browse/DMP-1048
Request Audio Scenarios and Steps
```
[ ] Yes
[ X] No
```
=> DMP-1048 Request Audio Scenarios and steps

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-1135
Added scenario for Case Search errors.
Added coverage for various other tickets, mostly small changes as part of logical flow.
```
[ ] Yes
[x] No
```
=> DMP-1135 Case Search Errors

src/main/java/uk/gov/hmcts/darts/automation/utils/Database.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Postgres.java, src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_db.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java
=> DMP-1467 minor fixes

src/main/java/uk/gov/hmcts/darts/automation/utils/ApiResponse.java, src/main/java/uk/gov/hmcts/darts/automation/utils/SoapApi.java, src/main/java/uk/gov/hmcts/darts/automation/utils/TestData.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_soapApi.java, src/test/resources/environment.properties
Encode entities in  SOAP messages with SOAPAction
```
[ ] Yes
[x] No
```
=> DMP-1467 minor updates and fixes

src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_navigation.java, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
N/A
Fixes made for failing case search scenario
```
[ ] Yes
[x] No
```
=> DMP-697 Fixes for Case Search

Jenkinsfile_CNP, Jenkinsfile_nightly, src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java, src/test/resources/cucumber/features/portal/DARTS_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Portal.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Requester.feature, src/test/resources/cucumber/features/portal/DARTS_Requester_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Restricted_Page_Access.feature
https://tools.hmcts.net/jira/browse/DMP-1025
https://tools.hmcts.net/jira/browse/DMP-925
https://tools.hmcts.net/jira/browse/DMP-1479
```
[ ] Yes
[ X] No
```
=> DMP-1059 your transcripts

src/main/java/uk/gov/hmcts/darts/automation/model/responses/Info.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Database.java, src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/JsonApi.java, src/main/java/uk/gov/hmcts/darts/automation/utils/JsonString.java, src/main/java/uk/gov/hmcts/darts/automation/utils/JsonUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java, src/main/java/uk/gov/hmcts/darts/automation/utils/SoapApi.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Substitutions.java, src/main/java/uk/gov/hmcts/darts/automation/utils/TestData.java, src/main/java/uk/gov/hmcts/darts/automation/utils/XmlString.java, src/main/java/uk/gov/hmcts/darts/automation/utils/XmlUtils.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_db.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_hooks.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_navigation.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_prompt.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_soapApi.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_testData.java, src/test/resources/cucumber/features/portal/DARTS_Portal.feature, src/test/resources/environment.properties, src/test/resources/testdata.properties
[
](https://tools.hmcts.net/jira/browse/DMP-1467)
Add XmlString class to build xml body for tests
```
[ ] Yes
[x] No
```
=> DMP-1467 Add XmlString class

src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature
https://tools.hmcts.net/jira/browse/DMP-868
Scenario created for DMP-868
```
[ ] Yes
[x] No
```
=> DMP-868 View Transcript Screen

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-561
Added coverage for DMP-561, may have to make further changes due to data changes.
```
[ ] Yes
[x] No
```
=> DMP-561 Amend Case Search

src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-1243
Scenarios for DMP-1243
```
[ ] Yes
[x ] No
```
=> Scenarios for DMP-1243

src/main/java/uk/gov/hmcts/darts/automation/utils/Substitutions.java
fix substitutions
```
[ ] Yes
[x] No
```
=> DMP-1467_corrections to substitutions

src/test/resources/cucumber.features.api/DARTS_Cases_API.feature, src/test/resources/cucumber.features.api/DARTS_Transcription_API.feature, src/test/resources/cucumber.features.endtoend/DARTS_End_to_End.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature
https://tools.hmcts.net/jira/browse/DMP-1331
Scenarios for DMP-1331
```
[ ] Yes
[ X] No
```
=> Scenarios for DMP-1331

.gitignore, src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/JsonApi.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Substitutions.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java
Changes to substitute date
```
[ ] Yes
[x] No
```
=> DMP-1467_minor updates and fixes

src/test/resources/cucumber.features.api/DARTS_Courthouses_API.feature, src/test/resources/cucumber.features.api/DARTS_Transcription_API.feature, src/test/resources/cucumber.features.endtoend/DARTS_End_to_End.feature
https://tools.hmcts.net/jira/browse/DMP-746
https://tools.hmcts.net/jira/browse/DMP-1250
Scenarios for API courthouse endpoints
```
[ ] Yes
[X ] No
```
=> DMP-746_POST_Courthouse

src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-1255
Scenarios for DMP-1255
```
[ ] Yes
[ X] No
```
=> DMP-1255TranscribersYourWorkToDoScreen

src/test/resources/cucumber/features/portal/DARTS_Approver.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-1815
Scenario for DMP-1815
```
[ ] Yes
[ x] No
```
=> Scenario for DMP-1815

src/test/resources/cucumber/features/portal/DARTS_Requester.feature
https://tools.hmcts.net/jira/browse/DMP-1028
Scenarios for DMP-1028
```
[ ] Yes
[x] No
```
=> Scenarios for DMP-1028

src/test/resources/cucumber.features.api/DARTS_Transcription_API.feature
DMP-1335
DMP-1336
https://tools.hmcts.net/jira/browse/DMP-1598
https://tools.hmcts.net/jira/browse/DMP-1335
https://tools.hmcts.net/jira/browse/DMP-1336
```
[ ] Yes
[X ] No
```
=> DMP-1598_Transcription_Sort_Order

src/test/resources/cucumber/features/portal/DARTS_Requester.feature
https://tools.hmcts.net/jira/browse/DMP-1053
Scenario created for DMP-1053
```
[ ] Yes
[x] No
```
=> DMP-1053 Delete Single Transcript Request

src/test/resources/cucumber/features/portal/DARTS_Requester.feature
https://tools.hmcts.net/jira/browse/DMP-1054
Scenario created for DMP-1054
```
[ ] Yes
[x] No
```
=> DMP-1054 Delete Multiple Transcript Requests

src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber.features.JsonApi/DARTS_AudioRequests_API.feature, src/test/resources/cucumber.features.JsonApi/DARTS_Audio_API.feature
https://tools.hmcts.net/jira/browse/DMP-982
https://tools.hmcts.net/jira/browse/DMP-1271
https://tools.hmcts.net/jira/browse/DMP-1169
https://tools.hmcts.net/jira/browse/DMP-777
StepDef GET Request with Headers
DMP-777
DMP-1169
DMP-982
DMP-1271
```
[ ] Yes
[X ] No
```
=> Dmp 1169 preview audio

src/test/resources/cucumber/features/portal/DARTS_Judge.feature
https://tools.hmcts.net/jira/browse/DMP-1618
Scenario for judges having permissions to be able to view and request transcripts
```
[ ] Yes
[x] No
```
=> DMP-1618 Scenario added

src/main/java/uk/gov/hmcts/darts/automation/utils/JsonApi.java
allow api parameters to have an empty value
```
[ ] Yes
[x] No
```
=> DMP-1467 allow empty header parameter to be used

src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_soapApi.java
implement dynamic data for soap messages supplied as a single string
```
[ ] Yes
[x] No
```
=> DMP-1467 dynamic data for full soap string

src/main/java/uk/gov/hmcts/darts/automation/utils/JsonApi.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber.features.JsonApi/DARTS_AudioRequests_API.feature, src/test/resources/cucumber.features.JsonApi/DARTS_DarPC.feature, src/test/resources/cucumber.features.SoapApi/DARTS_Cases_SoapAPI.feature
**Before creating a pull request make sure that:**
https://tools.hmcts.net/jira/browse/DMP-1730
https://tools.hmcts.net/jira/browse/DMP-1091
StepDef for PATCH
```
[ ] Yes
[X ] No
```
=> DMP-1168_audio_endpoint

src/test/resources/cucumber/features/portal/DARTS_Requester.feature
https://tools.hmcts.net/jira/browse/DMP-1740
Scenario for DMP-1740
```
[ ] Yes
[ X] No
```
=> Scenario for DMP-1740

src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature
https://tools.hmcts.net/jira/browse/DMP-1353
Scenario for DMP-1353 added
```
[ ] Yes
[x] No
```
=> DMP-1353 scenario added

src/main/java/uk/gov/hmcts/darts/automation/utils/JsonUtils.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber.features.JsonApi/DARTS_Cases_API.feature, src/test/resources/cucumber.features.SoapApi/DARTS_Cases_SoapAPI.feature, src/test/resources/cucumber.features.endtoend/DARTS_End_to_End.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-1927
Step def to add courtlogs
```
[ ] Yes
[ X] No
```
=> DMP-1927_AdvanceSearch

src/test/resources/cucumber/features/portal/DARTS_Case_File_Screen.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-1606
Testing ensuring the restriction banner is working as expected in the Case File Screen
```
[ ] Yes
[X] No
```
=> Dmp 1606 enhancement case file screen

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-1397
Scenarios for DMP-1397
```
[ ] Yes
[X] No
```
=> Scenarios for DMP-1397

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-1798
Scenarios for DMP-1798
```
[ ] Yes
[X] No
```
=> Scenarios for DMP-1798

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-2095
- Multiple scenarios now using dynamic data, created at start of feature. All scenarios that rely on this data are tagged with regression tag.
- New scenario for combined simple and advanced search, superseding the previous two scenarios.
- All other scenarios updated to either use dynamic data or fixed to pass due to data changes.
```
[ ] Yes
[x] No
```
=> DMP-2095 Case Search Feature Updates

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
- Changed data setup to include one case with a restriction on it, adds layer of coverage and variety.
- Three scenarios altered to use the restricted case rather than static data.
```
[ ] Yes
[x] No
```
=> Additional updates to Case Search

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/JsonApi/DARTS_Events.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-2055
End to end Scenario for Transcriber
```
[ ] Yes
[ X] No
```
=> Dmp 2055 e2e transcriber

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-2206
Scenario for Requester
```
[ ] Yes
[ X] No
```
=> DMP-2055_e2e_transcriber

src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature
https://tools.hmcts.net/jira/browse/DMP-2212
- 10/13 scenarios reworked to use dynamic data
- Remaining 3 scenarios reworked to work without background
```
[ ] Yes
[x] No
```
=> DMP-2212 Scenarios updated

Jenkinsfile_CNP, Jenkinsfile_nightly
=> Fixing HTML report directory in Jenkinsfiles

Jenkinsfile_CNP, Jenkinsfile_nightly
Added Tags for the functional tests for Jenkins
```
[ ] Yes
[X ] No
```
=> Added Tags for the functional tests for Jenkins

.gitignore, Jenkinsfile_CNP, Jenkinsfile_nightly, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature, src/test/resources/cucumber/features/portal/DARTS_Internal_Login.feature, src/test/resources/cucumber/features/portal/DARTS_Restricted_Page_Access.feature
Corrected Tags for the Jenkins file
```
[ ] Yes
[X ] No
```
=> Corrected Tags for the Jenkins file

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java
radio buttons not found on 1st page (external/internal login)
Changed to click on labels rather than radio buttons as labels overlap the buttons at the point selenium clicks
```
[ ] Yes
[x] No
```
=> DMP-2258_radio buttons not found on 1st page

src/test/resources/cucumber/features/portal/DARTS_Requester.feature
**Before creating a pull request make sure that:**
https://tools.hmcts.net/jira/browse/DMP-2124
Update multiple remove transcripts check
```
[ ] Yes
[ x] No
```
=> DMP-2124 ready for review

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature
- Reworked checkbox and radio button steps after Preksha's changes
- Old steps commented in case of revert to old Gherkin, can be removed if new ones work
- Restriction table checks changed
```
[ ] Yes
[x] No
```
=> Additional fixes for nightly run

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-1899
DMP-1899_Scenario for default retention policy 
```
[ ] Yes
[X] No
```
=>  DMP-1899_Scenario for default retention policy 

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Credentials.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_base.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_soapApi.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature
move 2 methods to stepdef_base
fix end2end scenarios
wait for audio to be available
```
[ ] Yes
[x] No
```
=> Dmp 2258 test automation framework maintenance

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature
fix scenario in e2e test
portal class changes
```
[ ] Yes
[x] No
```
=> DMP-2258 test automation framework maintenance

src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_External_Login.feature, src/test/resources/cucumber/features/portal/DARTS_Internal_Login.feature, src/test/resources/cucumber/features/portal/DARTS_Portal.feature, src/test/resources/cucumber/features/portal/DARTS_Restricted_Page_Access.feature
Changes for demo and nightly runs
```
[ ] Yes
[X ] No
```
=> Changes for demo and nightly runs

src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature
https://tools.hmcts.net/jira/browse/DMP-2360
- All but scenario now use dynamic data, created at start of feature. All scenarios that rely on this data are tagged with regression tag.
- Old scenarios that were superseded removed, old coverage is still maintained while extended coverage for whole E2E added.
```
[ ] Yes
[x] No
```
=> DMP-2360 Request Transcript Rework

src/test/resources/cucumber/features/portalAdmin/admin.feature
https://tools.hmcts.net/jira/browse/DMP-634
DMP-634-Search for Users in the Admin Portal Primary page
```
[ ] Yes
[ X] No
```
=>  DMP-634-Search for Users in the Admin Portal Primary page

bin/secrets-stg.sh, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature, src/test/resources/testdata.properties
=> DMP-2258 fix scenarios

src/test/resources/cucumber/features/portalAdmin/admin.feature
https://tools.hmcts.net/jira/browse/DMP-725
https://tools.hmcts.net/jira/browse/DMP-725
```
[ ] Yes
[ X] No
```
=>  DMP-725-Courthouse Search Page

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Judge.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-1612
DMP-1612-Delete Annotation Screen
```
[ ] Yes
[x] No
```
=> DMP-1612-Delete Annotation Screen

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-1616
DMP-1616-Add annotation screen
```
[ ] Yes
[X] No
```
=> DMP-1616-Add annotation screen

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-1614
DMP-1614-Annotation Template
```
[ ] Yes
[X] No
```
=> DMP-1614-Annotation Template

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-1623
DMP-1623-Add annotation confirmation screen
```
[ ] Yes
[X] No
```
=> DMP-1623-Add annotation confirmation screen

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-2246
DMP-2246-Annotation-download the document
```
[ ] Yes
[x ] No
```
=>  DMP-2246-Annotation-download the document

src/main/java/uk/gov/hmcts/darts/automation/utils/JsonApi.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/environment.properties
StepDef to POST with query params
Substitutions in navigation shared
Changes from https to http for DARTS gateway
```
[ ] Yes
[ X] No
```
=> StepDef to process dailylist

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-724
DMP-724-Update user personal details
```
[ ] Yes
[X] No
```
=> DMP-724-Update user personal details

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2222
Scenario for DMP-2222
```
[ ] Yes
[x] No
```
=> DMP-2222-Viewing a users group

src/test/resources/cucumber/features/portal/DARTS_Case_Retention.feature
https://tools.hmcts.net/jira/browse/DMP-1413
- Scenario added for DMP-1413 around case retention, all AC covered.
- Minor adjustments and tidying up
```
[ ] Yes
[x] No
```
=> DMP-2138 Case Retention Scenario

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2224
Scenarios for DMP-2224, DMP-2348 and DMP-2225.
```
[ ] Yes
[x] No
```
=> DMP-2224-Removing a group confirmation screen

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature
N/A
- Fixes for failing regression tests (Case Search and Request Audio)
- Changed data for some tests which were clashing with others
- Reran tests and passed locally
```
[ ] Yes
[x] No
```
=> Fixes for failing regression tests

src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-2300
message displayed when audio hasn't reached unstructured data store
```
[ ] No
```
=> Dmp 2300 message displayed when audio hasn't reached unstructured data store

src/test/resources/cucumber/features/portal/DARTS_Case_Retention.feature
https://tools.hmcts.net/jira/browse/DMP-1437
https://tools.hmcts.net/jira/browse/DMP-1439
```
[ ] Yes
[ X] No
```
=> DMP-1437 & DMP-1439

src/test/resources/cucumber/features/portal/DARTS_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature
https://tools.hmcts.net/jira/browse/DMP-2651
- One scenario covered already in different feature file, moved tag to reflect this.
- Multiple scenarios made obsolete by improved single scenario with dynamic data.
- Clean up and tidying.
```
[ ] Yes
[x] No
```
=> DMP-2651 Approver Rework

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2186
Creating a courthouse - Check details
```
No
```
=> DMP-2186 Creating a Courthouse - Check Details Ready for Review

src/test/resources/cucumber/features/portal/DARTS_Judge.feature
https://tools.hmcts.net/jira/browse/DMP-2673
- Scenario added that made existing two scenarios obsolete while using dynamic data and providing more coverage.
- Ran locally and passed.
```
[ ] Yes
[x] No
```
=> DMP-2673 Judge Rework

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
N/A
- Minor changes to fix a handful of failing regression tests
```
[ ] Yes
[x] No
```
=> Regression fixes

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2466
Scenarios for DMP-2466-Retention Policies Primary Page
```
[ ] Yes
[X ] No
```
=> DMP-2466-Retention Policies Primary Page

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-1192
View Courthouse (Details Tab)
```
[ ] No
```
=> DMP-1192 View Courthouse

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2299
Viewing Group Details
```
[ ] No
```
=> DMP-2299 Viewing Group Details

src/main/java/uk/gov/hmcts/darts/automation/utils/SoapApi.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java
Update stepdef to make 'the's optional in 
@Then("I wait for (the )text {string} on (the )same row as (the )link {string}")
```
[ ] Yes
[x] No
```
=> DMP-2258 Update stepdef for wait

src/main/java/uk/gov/hmcts/darts/automation/utils/SoapApi.java
fix authentication for soap
```
[ ] Yes
[x] No
```
=> DMP-2258 fix authentication for soap

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2302
Edit a group
```
[ ] No
```
=> Dmp 2302 edit a group

src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature
Advance Search changes
```
[ ] Yes
[X ] No
```
=> Final changes to Advance Search

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2269
https://tools.hmcts.net/jira/browse/DMP-2581
DMP-2581 Viewing groups - Adding a user
DMP-2269 Courthouse search results page
```
[ ] Yes
[ X] No
```
=> DMP-2269 & DMP-2581 is ready for review.

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2305?filter=-1
Scenarios for DMP-2305
```
[ ] Yes
[X] No
```
=> DMP-2305-Viewing group details - Users

src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature, src/test/resources/cucumber/features/portal/DARTS_Portal.feature, src/test/resources/testdata.properties
Changes to Requester End to End Scenario
```
[ ] Yes
[ X] No
```
=> DMP-2114_requester_changes

src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-2201
Changes to Approver end-to-end Scenario
```
[ ] Yes
[ X] No
```
=> Changes to Approver end to end Scenario

src/main/java/uk/gov/hmcts/darts/automation/utils/HtmlTable.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_htmlTable.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-2055
Step Definition to click on table header of a table
Changes to Scenarios of Transcriber
```
[ ] Yes
[ X] No
```
=> DMP-2055_transcriber

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2317
Create new group (Translation QA or Transcriber)
```
[ ] No
```
=> Dmp 2317 create a new group

src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature
https://tools.hmcts.net/jira/browse/DMP-2751
- Scenarios which were already better covered in other feature file, moved tags to reflect this and removed obsolete scenarios.
- Multiple other scenarios made obsolete by improved single scenario with dynamic data.
- Clean up and tidying.
```
[ ] Yes
[x] No
```
=> DMP-2751 Transcriber Only rework

src/main/java/uk/gov/hmcts/darts/automation/utils/HtmlTable.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-2056
Changes to function to click on HTML table header
End to end Scenario for Language Shop User
```
[ ] Yes
[X ] No
```
=> DMP-2056_Language_shop

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java
Step Def to look for Med ID
```
[ ] Yes
[ X] No
```
=> DMP-2798 wait for requested audio mer_id to be ready

src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature
https://tools.hmcts.net/jira/browse/DMP-2751
- Finished updating other scenarios as part of rework.
- Tags/ticket coverage updated, comments added where appropriate.
- Added line from Preksha's changes, may need further updates to pass.
```
[ ] Yes
[x] No
```
=> DMP-2751 Transcriber Only rework part 2

src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature
https://tools.hmcts.net/jira/browse/DMP-2200
```
[ ] Yes
[ X] No
```
=> Changes in e2e Judge to create cases using Dailylist

src/main/java/uk/gov/hmcts/darts/automation/utils/XmlUtils.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature, src/test/resources/cucumber/features/portal/DARTS_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Retention.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Judge.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/testdata.properties
Changes in Step Definitions for addCase to add courtroom as well
Change scenarios to incorporate that
```
[ ] Yes
[X ] No
```
=> Changes in Step Definitions for addCase to add courtroom as well

src/test/java/uk/gov/hmcts/darts/automation/cucumber/testRunner/TestRunner_Cucumber.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature
Commented include tags in TestRunner
```
[ ] Yes
[ X] No
```
=> DMP-2200_judge_e2e

src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature
https://tools.hmcts.net/jira/browse/DMP-2904
Advance_Search_rework for End to end Scenario
```
[ ] Yes
[X ] No
```
=> DMP-2904_Advance_Search_rework

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
N/A
- Fixes for new points based criteria for case search.
```
[ ] Yes
[x] No
```
=> Fixes for new case search points based criteria

src/main/java/uk/gov/hmcts/darts/automation/utils/JsonUtils.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/testdata.properties
Added "is_mid_tier" mandatory field to Events Step Def using json
```
[ ] Yes
[ X] No
```
=> Added "is_mid_tier" mandatory field to Events Step Def using json

src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature
https://tools.hmcts.net/jira/browse/DMP-2740
- Added checks for "From" row to see who made the transcript request in existing scenario.
```
[ ] Yes
[x] No
```
=> DMP-2740 Transcript Requester From

src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/testdata.properties
Judge_e2e Changed error message when Case is not found
Advance Search Changes
Judge data creation changes
```
[ ] Yes
[ ] No
```
=> DMP-2955_test_maintenance

src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portal/DARTS_Annotation.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature
https://tools.hmcts.net/jira/browse/DMP-2474
https://tools.hmcts.net/jira/browse/DMP-2562
https://tools.hmcts.net/jira/browse/DMP-2639
Create new retention policy version
Super user and Super Admin can request download audio
Check for global or courthouse Judge role before fetching annotations
```
[ ] Yes
[ X] No
```
=> Admin Portal Retention Policy

src/test/resources/cucumber/features/portal/DARTS_Language_Shop_User.feature
https://tools.hmcts.net/jira/browse/DMP-2137
Translation QA User permissions
```
[ ] No
```
=> DMP-2137 Translation QA user permissions

src/test/resources/cucumber/features/portal/DARTS_Super_User.feature
https://tools.hmcts.net/jira/browse/DMP-2404
New Role - Create Super User
```
[ ] Yes
[ x] No
```
=> Super User & Super Admin feature

src/test/resources/cucumber/features/portal/DARTS_Admin_Transcripts.feature
https://tools.hmcts.net/jira/browse/DMP-1265
- New feature and scenarios created to cover change of transcript workflow on Admin.
- Note this PR also covers DMP-2525 and DMP-2538. There are likely other tickets as well which will get tagged in a subsequent PR.
```
[ ] Yes
[x] No
```
=> DMP-1265 Change workflow status

src/test/resources/cucumber/features/portal/DARTS_Admin_Transcripts.feature, src/test/resources/cucumber/features/portal/DARTS_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Judge.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature
https://tools.hmcts.net/jira/browse/DMP-2525
- Change made after checking correct behaviour with BA/Dev.
- Adjustments to scenario, cleanup and uncommented lines.
- Changes to multiple features with approver flow, as approver now has two tabs on "Transcript Requests" section.
```
[ ] Yes
[x] No
```
=> DMP-2525-Part2 Admin Transcript Status Change

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/AdminPortal.java, src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_adminPortal.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_hooks.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_navigation.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/portal/DARTS_Portal.feature
Enhance portal smoketests:
- Check & click all menu & submenu links
- Cookie option on login screen verified
```
[ ] Yes
[x] No
```
=> DMP-2798_Enhance portal smoketest

src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
https://tools.hmcts.net/jira/browse/DMP-2931
- Scenario added for DMP-2931.
```
[ ] Yes
[x] No
```
=> Dmp 2931 remove user role

src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature
N/A
- Minor adjustments made, capitalisation issue on approver
- Added "Given I authenticate from the CPP source system" step and changed audio file to sample1.mp2
```
[ ] Yes
[x] No
```
=> Regression fixes - Single feature test

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2959
Add error messaging to Search Transcript screen
```
[ ] No
```
=> DMP-2959 Error Messaging for Search Transcript Screen

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-2746
Add and view event mapping
```
[ ] Yes
[ X] No
```
=> Add and view event mapping

src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature
extra scenarios for events
fix error
```
[ ] Yes
[x] No
```
=> DMP-2798_extra event scenarios & fixes

src/test/resources/cucumber/features/portal/DARTS_Admin_Transcripts.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
https://tools.hmcts.net/jira/browse/DMP-2323
Redid this PR as I had merge issues earlier with some extra changes:
- Coverage for DMP-2323.
- Tagging and line comments for other coverage, minor tweaks
```
[ ] Yes
[X] No
```
=> DMP-2323 Deactivate User

src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
https://tools.hmcts.net/jira/browse/DMP-2678
- Coverage for DMP-2678 in the form of one scenario.
- Added regression tags to most of the scenarios in DARTS_admin.feature to add them to the pack after running locally and passing.
- Changes made to reflect different landing page to before.
```
[ ] Yes
[X] No
```
=> DMP-2678 Transformed media search

src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/test/resources/cucumber/features/portal/DARTS_Case_Retention.feature, src/test/resources/cucumber/features/portal/DARTS_Portal.feature, src/test/resources/testdata.properties
https://tools.hmcts.net/jira/browse/DMP-3249
Case Retention
```
[ ] Yes
[X ] No
```
=> DMP-3249_case_retention

src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Transcripts.feature
https://tools.hmcts.net/jira/browse/DMP-3133
- Scenario updated to cover this ticket, new scenario not required.
```
[ ] Yes
[X] No
```
=> DMP-3133 Transcript request status changes

src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
https://tools.hmcts.net/jira/browse/DMP-2679
https://tools.hmcts.net/jira/browse/DMP-2695
Transformed media-change over & detail page
```
[ ] Yes
[x ] No
```
=> Transformed media-change over & detail page

src/test/resources/cucumber/features/SoapApi/DARTS_DailyList.feature, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature
https://tools.hmcts.net/jira/browse/DMP-3245
Dailylist - cases with a Time Marking note after noon cause exceptions
Add a daily list with timemarkingnote 3:00 PM
```
[ ] Yes
[x] No
```
=> DMP-3245 Daily list timemarkingnote 3:00 PM

src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature
https://tools.hmcts.net/jira/browse/DMP-1928 
Add in an automated test scenario for CPP Poll Check messages into the DARTS_Events.feature file. 
```
[ ] Yes
[X] No
```
=> DMP-1928: Added in XHIBIT poll check test scenario

src/test/resources/cucumber/features/SoapApi/DARTS_DailyList.feature, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature
soap event tests broken
```
[ ] Yes
[x] No
```
=> DMP-3245_daily list with pm time marking note

src/test/resources/cucumber/features/portal/DARTS_Annotation.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Retention.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Transcripts.feature
N/A
- Temporary changes to Admin transcript scenario to make it run further until hour offset solution is decided. Defect found as a result.
- Fixes to failing scenarios.
```
[ ] Yes
[x] No
```
=> Regression adjustments

src/main/java/uk/gov/hmcts/darts/automation/utils/SoapApi.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Substitutions.java, src/main/java/uk/gov/hmcts/darts/automation/utils/XmlUtils.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_soapApi.java, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature, src/test/resources/cucumber/features/SoapApi/DARTS_GetCases.feature, src/test/resources/cucumber/features/SoapApi/DARTS_RegisterNode.feature, src/test/resources/environment.properties
https://tools.hmcts.net/jira/browse/DMP-3455
https://tools.hmcts.net/jira/browse/DMP-3453
https://tools.hmcts.net/jira/browse/DMP-3454
https://tools.hmcts.net/jira/browse/DMP-3405
CHANGED DARTS PROXY ADDRESS TO USE GATEWAY UNTIL CDATA ISSUES ARE RESOLVED
Added registerNode
Changed & added methods in XmlUtils
New methods in Substitutions to create IP & MAC addresses based on run no
Changed events feature to use daily list rather than add case so that the hearing already exists
```
[ ] Yes
[x] No
```
=> DMP-3405_Increase SOAP test coverage

src/test/resources/cucumber/features/portal/DARTS_Restricted_Page_Access.feature
https://tools.hmcts.net/jira/browse/DMP-2975
- Scenario added for DMP-2975 (also covers DMP-2974)
```
[ ] Yes
[x] No
```
=> DMP-2975 User State

src/test/resources/cucumber/features/portal/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-3234
Scenarios for DMP-3234,3235,2728 AND 3129.
```
[ ] Yes
[ x] No
```
=> DMP-3234-Add A Link To User Portal Link To Each Admin Portal Screen

src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
https://tools.hmcts.net/jira/browse/DMP-3315
Admin Portal - Hearings search results
```
[ ] Yes
[x ] No
```
=> Admin Portal - Hearings search results

Jenkinsfile_nightly
Increase nightly runtime
```
[ ] Yes
[X ] No
```
=> Increase nightly runtime

Jenkinsfile_nightly, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature
Fix for Advance Search
```
[ ] Yes
[X ] No
```
=> Fix for Advance Search

src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
https://tools.hmcts.net/jira/browse/DMP-3406
https://tools.hmcts.net/jira/browse/DMP-3469
Update Transcript results
```
[ ] Yes
[X ] No
```
=> Update Transcript results

src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/testdata.properties
Fix for language shop user
```
[ ] Yes
[ X] No
```
=> Fix for language shop user

src/main/java/uk/gov/hmcts/darts/automation/utils/XmlUtils.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_soapApi.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/testRunner/TestRunner_Cucumber.java, src/test/resources/cucumber/features/SoapApi/DARTS_AddCourtlog.feature, src/test/resources/cucumber/features/SoapApi/DARTS_DailyList.feature, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature, src/test/resources/cucumber/features/SoapApi/DARTS_TranscriptionEvents.feature, src/test/resources/environment.properties
https://tools.hmcts.net/jira/browse/DMP-3455
new method to remove CDATA tags & encode contents
Verify case doesnt exists before addCase tests
```
[ ] Yes
[x] No
```
=> DMP-355_use_darts_proxy

src/test/resources/cucumber/features/SoapApi/DARTS_TranscriptionEvents.feature
fix transcription event feature
```
[ ] Yes
[x] No
```
=> DMP-3455_fix_transcription_events

src/main/java/uk/gov/hmcts/darts/automation/utils/XmlUtils.java, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature, src/test/resources/environment.properties
https://tools.hmcts.net/jira/browse/DMP-3455
Temporarily point automation at gateway rather than darts proxy
fix addAudio xml method
extra scenario for events
```
[ ] Yes
[x] No
```
=> DMP-3455 use gateway instead of darts proxy temporarily

src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java, src/test/resources/environment.properties
Change sequence no prefix as tests are hitting a number of existing cases
```
[ ] Yes
[x] No
```
=> DMP-3455 Change sequence no prefix used in tests

src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
change to dateUtils class - retention date
some fixes to admin screens
```
[ ] Yes
[x] No
```
=> DMP-2798_method & feature fixes

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
https://tools.hmcts.net/jira/browse/DMP-2963
Add court log into the case file screen and replaced Judge name with JUDGE 
```
[ ] Yes
[x ] No
```
=> DMP-2963 add a court log tab to the case file screen

src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/main/java/uk/gov/hmcts/darts/automation/utils/SeleniumWebDriver.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Substitutions.java, src/main/java/uk/gov/hmcts/darts/automation/utils/TestData.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_hooks.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_soapApi.java, src/test/resources/cucumber/features/JsonApi/DARTS_Events.feature, src/test/resources/cucumber/features/SoapApi/DARTS_DailyList.feature, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature, src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portal/DARTS_Portal.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature, src/test/resources/environment.properties
add edge & firefox
```
[ ] Yes
[x] No
```
=> DMP-2798_Add edge & firefox, use darts proxy again except audio

src/test/java/uk/gov/hmcts/darts/automation/cucumber/testRunner/TestRunner_Cucumber.java, src/test/resources/cucumber/features/SoapApi/DARTS_RegisterNode.feature, src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Retention.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Judge.feature, src/test/resources/cucumber/features/portal/DARTS_Language_Shop_User.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature, src/test/resources/cucumber/features/portal/DARTS_Super_User.feature, src/test/resources/environment.properties
Scenario fixes including more DB change fixes
Add review tag for scenarios to omit until resolved
```
[ ] Yes
[x] No
```
=> DMP-2798 scenario fixes & move others to review

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/AdminPortal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_adminPortal.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_navigation.java, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
changed waitForPageLoad method 
added waitForPageLoad to several methods where fields are clicked
updated admin feature to allow for test failure not breaking it
```
[ ] Yes
[x] No
```
=> DMP-2798_waitForPageLoad updates & admin feature fix

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/DbUtils.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_db.java, src/test/resources/cucumber/features/SoapApi/DARTS_DailyList.feature, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature, src/test/resources/cucumber/features/SoapApi/DARTS_TranscriptionEvents.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature
wait for daily list processing to complete by looking to see if there are any NEW DLs in teh database
```
[ ] Yes
[x] No
```
=> DMP-2798_wait for daily list processing to complete

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/DbUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Substitutions.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_db.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber/features/SoapApi/DARTS_DailyList.feature, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature, src/test/resources/cucumber/features/SoapApi/DARTS_TranscriptionEvents.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature, src/test/resources/cucumber/features/portal/DARTS_Super_User.feature
DMP-2798
retry daily list processing if conflict occurs
```
[ ] Yes
[x] No
```
=> DMP-2798_retry daily list processing if conflict occurs

src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/HtmlTable.java, src/main/java/uk/gov/hmcts/darts/automation/utils/JsonUtils.java
DMP-2798
use UTC time in json addAudio api call
```
[ ] Yes
[x] No
```
=> DMP-2798_use UTC time in json addAudio api call

src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
https://tools.hmcts.net/jira/browse/DMP-3309
View Event Id Screen
```
[ ] Yes
[ x] No
```
=> View Event Id Screen

src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature
Fix dates for timezone on jenkins (UTC) as well as local for database verifications
Change waiting for a successful daily list processed (not a 409 - conflict)
```
[ ] Yes
[x] No
```
=> DMP-2798_Fix dates for timezone on jenkins

src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_navigation.java, src/test/resources/cucumber/features/portal/DARTS_Super_User.feature
[DMP-3810](https://tools.hmcts.net/jira/browse/DMP-3810)
- Update some date formatters to include the Locale.ENGLISH
- Add a date formatter to format with `/` as in `30/12/2020`
- Update the super_user.feature tests
- Implement initial automation tests for SUPER_USER permissions
- Add a step definition to help clicking a dynamic link of a table
```
[ ] Yes
[x] No
```
=> DMP-3810 - SUPER_USER permission automation tests

src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Substitutions.java, src/main/java/uk/gov/hmcts/darts/automation/utils/TestData.java, src/test/resources/cucumber/features/SoapApi/DARTS_AddCourtlog.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Judge.feature, src/test/resources/cucumber/features/portal/DARTS_Requester_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/cucumber/features/portal/DARTS_Your_Audio.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Transcripts.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
DMP-2798
Jenkins fixes
```
[ ] Yes
[x] No
```
=> DMP-2798_scenario fixes

src/test/resources/cucumber/features/SoapApi/DARTS_GetCases.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature
DMP-2798
Fix features for jenkins
```
[ ] Yes
[x] No
```
=> DMP-2798_fix features

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Database.java, src/main/java/uk/gov/hmcts/darts/automation/utils/SeleniumWebDriver.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature
Feature fixes & some changes to classes
```
[ ] Yes
[x] No
```
=> DMP-2798 changes & fixes

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/HtmlTable.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/main/java/uk/gov/hmcts/darts/automation/utils/WaitUtils.java, src/test/resources/cucumber/features/SoapApi/DARTS_AddCase.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature, src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portal/DARTS_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Retention.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Portal.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Super_User.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Transcripts.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature, src/test/resources/testdata.properties
This Git Diff showcases various changes across multiple Java files and feature files within a project related to automation testing. The changes include method updates, logging improvements, and modifications to test scenarios, particularly in the handling of user interactions and validations.
1. **Portal.java**
- Updated a condition from checking size with `.size() == 0` to using `.isEmpty()` for clarity.
2. **HtmlTable.java**
- Enhanced error logging when there is a value mismatch in table data by providing more detailed messages.
3. **NavigationShared.java**
- Refactored methods for clicking links to improve readability and maintainability.
- Introduced a new method to wait for clickable elements using `By` selectors.
4. **WaitUtils.java**
- Added an overloaded method to wait for …
=> Fixed a number of tests / identified why other tests were failing

src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
https://tools.hmcts.net/jira/browse/DMP-2471
https://tools.hmcts.net/jira/browse/DMP-2475
Create and Edit Retention Policy
```
[ ] Yes
[ X] No
```
=> Create and Edit Retention Policy

src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature, src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Retention.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Transcripts.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
DMP-2798
feature fixes from jenkins fails
```
[ ] Yes
[x] No
```
=> DMP-2798_feature fixes

src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_admin.feature
DMP-2798
Feature updates
Includes fixes to avoid event versioning changes (re-using event_id & message_id)
```
[ ] Yes
[x] No
```
=> DMP-2798_Feature updates

README.md, src/test/resources/cucumber/features/portal/DARTS_Event_Versioning.feature
https://tools.hmcts.net/jira/browse/DMP-4034
https://tools.hmcts.net/jira/browse/DMP-4036
event versioning
```
[ ] Yes
[x] No
```
=> DMP-4034 DMP-4036 event versioning tests

src/main/java/uk/gov/hmcts/darts/automation/utils/Database.java, src/main/java/uk/gov/hmcts/darts/automation/utils/HtmlTable.java, src/test/resources/cucumber/features/portal/DARTS_Event_Versioning.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature
https://tools.hmcts.net/jira/browse/DMP-4035
Hide audio scenario
Also delete audio apart from actual delete
Fix for <td> elements in table header along with <th>
correction to table join
```
[ ] Yes
[x] No
```
=> DMP-4035 Hide audio tests

src/main/java/uk/gov/hmcts/darts/automation/utils/Database.java, src/main/java/uk/gov/hmcts/darts/automation/utils/DateUtils.java, src/main/java/uk/gov/hmcts/darts/automation/utils/HtmlTable.java, src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java, src/test/resources/cucumber/features/portal/DARTS_Event_Versioning.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature, src/test/resources/environment.properties
DMP-2798
Change sequence no generation for jenkins
```
[ ] Yes
[x] No
```
=> Dmp 4035 hide delete audio

src/test/resources/cucumber/features/SoapApi/DARTS_AddCase.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Event_Versioning.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Transcripts.feature
Update tags
```
[ ] Yes
[x] No
```
=> DMP-2798_Update feature tags

Jenkinsfile_CNP, Jenkinsfile_nightly, bin/secrets-stg.sh, src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Credentials.java, src/main/java/uk/gov/hmcts/darts/automation/utils/JsonApi.java, src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java
https://tools.hmcts.net/jira/browse/DMP-4066
Add second admin user - access as ADMIN2
```
[ ] Yes
[x] No
```
=> DMP-4066_add second admin user

src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/resources/cucumber/features/SoapApi/DARTS_AddCase.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature, src/test/resources/cucumber/features/portal/DARTS_Admin.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Audio.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature
https://tools.hmcts.net/jira/browse/DMP-4038
update tags
fix hide audio scenario
```
[ ] Yes
[x] No
```
=> DMP-2798_tag updates & scenario fixes

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/pageObjects/UcfTestHarness.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_hooks.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_jsonApi.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/SoapApi/DARTS_Events.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Judge.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_LanguageShop.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Requester.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Transcriber.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Transcripts.feature, src/test/resources/environment.properties
https://tools.hmcts.net/jira/browse/DMP-4247
DMP-4185 Feature updates
DMP-4185 increase timeouts
DMP-4185 add build changed warning to report
DMP-4247 Incorporate UCF test harness
DMP-4185 minor change - read properties
```
[ ] Yes
[x] No
```
=> DMP-4247_DMP-4185 UCF test harness & misc changes

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Database.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Groups.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_System_Configuration.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Users.feature
replace references to "there is an error" with verify error message
Change waits for audio request
Updates for logout & login - remove check for Sign in to the DARTS Portal
```
[ ] Yes
[x] No
```
=> DMP-4185 Update scenarios & methods

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Credentials.java, src/main/java/uk/gov/hmcts/darts/automation/utils/ReadProperties.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Users.feature
https://tools.hmcts.net/jira/browse/DMP-4284
change date range in search pagination - prevents > 500 search results
remove test tag
```
[ ] Yes
[x] No
```
=> DMP-4185_change date range in search pagination & remove test tag

src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Courthouse.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Groups.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Users.feature
https://tools.hmcts.net/jira/browse/DMP-4209
Back link added to view users, groups & courthouses
```
[ ] Yes
[x ] No
```
=> Back link added to view users, groups & courthouses

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/AdminPortal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/Database.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_adminPortal.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_hooks.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_navigation.java, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Users.feature
update button press method
add user-group table join
update admin user feature
```
[ ] Yes
[x] No
```
=> DMP-4185 fix button method & features

src/main/java/uk/gov/hmcts/darts/automation/utils/HtmlTable.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_htmlTable.java, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Retention_Policies.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Users.feature
New method for verification of html table allowing additional rows to be ignored
Fixed some admin scenarios
```
[ ] Yes
[x] No
```
=> DMP-4185 New method for html table comparison

src/main/java/uk/gov/hmcts/darts/automation/pageObjects/Portal.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/main/java/uk/gov/hmcts/darts/automation/utils/WaitUtils.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_db.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_portal.java, src/test/resources/cucumber/features/SoapApi/DARTS_DailyList.feature, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Users.feature
New methods to wait for error message 
new method to verify individual error message
new scenario to verify error messages when updating user details
other updates
```
[ ] Yes
[x] No
```
=> DMP-4185_verify individual error messages & user does not exist

Jenkinsfile_nightly
N/A
- run at 6:30pm
```
[ ] Yes
[ ] No
```
=> Nightly cron update

build.gradle, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Portal.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Courthouse.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Search.feature, src/test/resources/cucumber/features/portalAdmin/Darts_Admin_Transformed_Media.feature
N/A
- Coverage for DMP-4102.
- Coverage for DMP-4545.
- Coverage for DMP-4532.
- Other failing tests not relating directly to tickets updated.
```
[ ] Yes
[x] No
```
=> Tests updated to reflect recent changes

src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portal/DARTS_Request_Transcript.feature, src/test/resources/cucumber/features/portal/DARTS_Transcribers_Only.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Courthouse.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Search.feature, src/test/resources/cucumber/features/portalAdmin/Darts_Admin_Transformed_Media.feature
https://tools.hmcts.net/jira/browse/DMP-4318
- Features updated for DMP-4318.
- Coverage added for DMP-4129.
- Fixes for failing tests included.
```
[ ] Yes
[x] No
```
=> Updates for DMP-4318 and fixes

src/test/resources/cucumber/features/portal/DARTS_Your_Audio.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Search.feature
https://tools.hmcts.net/jira/browse/DMP-4442
Update Audio file hide/delete
```
[ ] Yes
[x] No
```
=> Audio hide/delete

src/main/java/uk/gov/hmcts/darts/automation/utils/HtmlTable.java, src/main/java/uk/gov/hmcts/darts/automation/utils/NavigationShared.java, src/test/java/uk/gov/hmcts/darts/automation/cucumber/steps/StepDef_htmlTable.java, src/test/resources/cucumber/features/endtoend/DARTS_End_to_End_Approver.feature, src/test/resources/cucumber/features/portal/DARTS_Case_Search.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Retention_Policies.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Search.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_System_Configuration.feature, src/test/resources/cucumber/features/portalAdmin/DARTS_Admin_Users.feature
N/A
- Fixes for a number of failing tests.
- Step and code for more flexible table checking, relates to verifyHtmlTableIncludesRowsOnAnyPage.
- Updated tags for coverage.
```
[ ] Yes
[x] No
```
=> Fixes for failed tests, step added for flexible table checks
